### ISSUE TITLE
Can you provide the model files for the first stage?

### ISSUE THREAD

**Issue by ghost** [liuzechun/AdamBNN#1]
I paid attention to your work very early and I admire you very much. I want to train from the second stage, so I would like to ask if you can provide the first stage model?

**Comment by liuzechun** [comment]
Hi, thank you for your interest in our work and your nice words. I uploaded the first stage model, please find it here: https://hkustconnect-my.sharepoint.com/:u:/g/personal/zliubq_connect_ust_hk/EahtDKdT-PVEuP6TVWCU1msBAjhWPwN3AdLZAw5ekHgB0A?e=SxcMAm

**Comment by ghost** [comment]
Thank you！

**Comment by TIEHua** [comment]
> I paid attention to your work very early and I admire you very much. I want to train from the second stage, so I would like to ask if you can provide the first stage model?

Sorry to bother you. I found the link of the first-stage model is unavailable. Have you tested the first-stage model? Could you please provide the accuracy of the first-stage model?
